/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\door\DOOR_B_1.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/DOOR_B_1.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.door001.geometry} material={materials['Baked_B_4.002']} position={[0.05, 0, 0.49]} />
      <group position={[0.02, 1.074, -0.561]}>
        <mesh geometry={nodes.Mesh_88002.geometry} material={materials.Blackhandle} />
        <mesh geometry={nodes.Mesh_88002_1.geometry} material={materials.numberkey} />
      </group>
      <group position={[0, 0, 0.5]}>
        <mesh geometry={nodes.Mesh_80005.geometry} material={materials['Baked_B_4.002']} />
        <mesh geometry={nodes.Mesh_80005_1.geometry} material={materials.Gold} />
      </group>
      <mesh geometry={nodes.door004.geometry} material={materials['Baked_B_4.002']} position={[0.039, 1.007, -0.435]} scale={[0.808, 0.081, 1]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.blaack} position={[0.037, 1.007, -0.342]} rotation={[0, 0, -Math.PI / 2]} scale={[0.099, 0.105, 0.105]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.ground} position={[0.044, 0, -0.193]} />
      <mesh geometry={nodes.door005.geometry} material={materials['Baked_B_4.002']} position={[0.044, 1.255, -0.09]} />
      <mesh geometry={nodes.door006.geometry} material={materials['Baked_B_4.002']} position={[0, 0, 0.5]} />
    </group>
  )
}

useGLTF.preload('/DOOR_B_1.gltf')
